# Check LHE File Event Weight

## 1. Import Packages

In [1]:
# The Python Standard Library
import os
import sys
import time
import datetime
import glob
import multiprocessing as mp

# The Third-Party Library
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tqdm
import prettytable
import uproot
import pyjet
import pylhe
import importlib

# My Packages
import myhep.particle_information_v2 as mypiv2
import myhep.analytical_function_v2 as myafv2
import myhep.particleinfo_v1 as mypiv1
import myhep.particlefun_v1 as myafv1

# increase figure showing resolution
%config InlineBackend.figure_format = 'retina'

## 2. Load the .lhe Data

In [2]:
INPUT_FILE_LHE = '/youwei_home/SVJ_CKKWL/s-channel_ckkwl-v2/s/Events/run_01/unweighted_events.lhe'

DATA_lhe = pylhe.readLHE(INPUT_FILE_LHE)

event_lhe = []
for event in DATA_lhe:
    event_lhe.append(event)

In [3]:
print("There are {} events in the LHE file.".format(len(event_lhe)))

There are 10000 events in the LHE file.


### 2-1. Look over the event weight in .lhe .weights branch

In [4]:
print(event_lhe[0])
print(event_lhe[1])

In [5]:
print(dir(event_lhe))
print('='*100)
print(dir(event_lhe[0]))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'attributes', 'eventinfo', 'optional', 'particles', 'visualize', 'weights']


In [6]:
print(event_lhe[0].weights)
print('='*100)
# print(event_lhe[0].weights[0])
print('='*100)
print(dir(event_lhe[0].weights))

None
['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']


In [7]:
for i in event_lhe[0].weights:
    print(i)

TypeError: 'NoneType' object is not iterable

In [8]:
print(event_lhe[1].weights)

None


In [9]:
for i in range(20):
    print(event_lhe[i].weights)

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


#### Conclusion: This way is failling.

### 2-2. Look over the event weight in the .lhe .eventinfo.weight branch 

In [10]:
print(event_lhe[0].eventinfo)
print(dir(event_lhe[0].eventinfo))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'aqcd', 'aqed', 'fieldnames', 'fromstring', 'nparticles', 'pid', 'scale', 'weight']


In [11]:
print(event_lhe[0].eventinfo.weight)
print(event_lhe[0].eventinfo.pid)

1.1548845
0.0


#### Alan's example

In [12]:
INPUT_FILE_LHE = '/youwei_home/SVJ_CKKWL/s-channel_ckkwl-v2/s/Events/run_01/unweighted_events.lhe'

svj = pylhe.readLHE(INPUT_FILE_LHE)

aaa = []
for i, event in enumerate(tqdm.tqdm(svj)):
    aaa.append(event.eventinfo.weight)
    
aaa = np.array(aaa)

10000it [00:05, 1907.60it/s]


In [13]:
aaa

array([1.1548845, 1.1548845, 1.1548845, ..., 1.1548845, 1.1548845,
       1.1548845])

In [14]:
np.where(aaa <= 0)

(array([ 345,  702,  875,  985, 1245, 1606, 2095, 2173, 2352, 2379, 2625,
        3014, 3031, 3278, 3305, 3796, 4390, 5452, 5538, 5695, 6303, 6355,
        6720, 6752, 6915, 6980, 7129, 7190, 7298, 7467, 7891, 8295, 8641,
        8846]),)

In [15]:
aaa[345]

-1.1548845

#### By myself

In [44]:
bbb = []

for i, event in enumerate(tqdm.tqdm(DATA_lhe)):
    bbb.append(event.eventinfo.weight)

0it [00:00, ?it/s]


In [40]:
DATA_lhe = pylhe.readLHE(INPUT_FILE_LHE)

bbb = []

for i, event in enumerate(tqdm.tqdm(DATA_lhe)):
    bbb.append(event.eventinfo.weight)

10000it [00:05, 1896.69it/s]


In [42]:
INPUT_FILE_LHE = '/youwei_home/SVJ_CKKWL/s-channel_ckkwl-v2/s/Events/run_01/unweighted_events.lhe'

svj = pylhe.readLHE(INPUT_FILE_LHE)

In [45]:
aaa = []
for i, event in enumerate(tqdm.tqdm(svj)):
    aaa.append(event.eventinfo.weight)
    
aaa = np.array(aaa)

0it [00:00, ?it/s]


In [17]:
DATA_lhe

<generator object readLHE at 0x7f94c2b51660>

In [18]:
svj

<generator object readLHE at 0x7f94a5c57270>

In [19]:
INPUT_FILE_LHE = '/youwei_home/SVJ_CKKWL/s-channel_ckkwl-v2/s/Events/run_01/unweighted_events.lhe'

DATA_lhe = pylhe.readLHE(INPUT_FILE_LHE)

bbb = []
for i, event in enumerate(tqdm.tqdm(DATA_lhe)):
    bbb.append(event.eventinfo.weight)
    
bbb = np.array(bbb)

10000it [00:06, 1645.53it/s]


In [20]:
np.sum(aaa - bbb)

0.0

#### Conclusion: ???

In [21]:
weight_ei = []

for i in range(len(event_lhe)):
    weight_ei.append(event_lhe[i].eventinfo.weight)
    
weight_ei = np.array(weight_ei)

In [22]:
for i in range(len(weight_ei)):
    if weight_ei[i] <= 0:
        print(i, weight_ei[i])

345 -1.1548845
702 -1.1548845
875 -1.1548845
985 -1.1548845
1245 -1.1548845
1606 -1.1548845
2095 -1.1548845
2173 -1.1548845
2352 -1.1548845
2379 -1.1548845
2625 -1.1548845
3014 -1.1548845
3031 -1.1548845
3278 -1.1548845
3305 -1.1548845
3796 -1.1548845
4390 -1.1548845
5452 -1.1548845
5538 -1.1548845
5695 -1.1548845
6303 -1.1548845
6355 -1.1548845
6720 -1.1548845
6752 -1.1548845
6915 -1.1548845
6980 -1.1548845
7129 -1.1548845
7190 -1.1548845
7298 -1.1548845
7467 -1.1548845
7891 -1.1548845
8295 -1.1548845
8641 -1.1548845
8846 -1.1548845


In [23]:
np.where(weight_ei <= 0)

(array([ 345,  702,  875,  985, 1245, 1606, 2095, 2173, 2352, 2379, 2625,
        3014, 3031, 3278, 3305, 3796, 4390, 5452, 5538, 5695, 6303, 6355,
        6720, 6752, 6915, 6980, 7129, 7190, 7298, 7467, 7891, 8295, 8641,
        8846]),)

### 2-3. Check these events are reasonable

In [26]:
print('{:^12}{:^9}{:^12}{:^12}{:^12}{:^12}{:^12}{:^12}{:^12}'.format('#','id','mother1','mother2','e','px','py','pz','status'))

for n in range(3):
    print("Event {}".format(n))
    for i, element in enumerate(event_lhe[n].particles):
        print('{:^12}{:^9.0f}{:^12.0f}{:^12.0f}{:^12.3f}{:^12.3f}{:^12.3f}{:^12.3f}{:^12.0f}'
          .format(i+1, element.id, element.mother1, element.mother2, element.e, element.px, element.py, element.pz, element.status))
    print('-'*102)

     #         id      mother1     mother2        e           px          py          pz        status   
Event 0
     1          1         0           0        580.441      0.000       0.000      580.441        -1     
     2         -1         0           0        978.983      -0.000      -0.000     -978.983       -1     
     3       5000001      1           2        1559.424     0.000       0.000      -398.541       2      
     4       4900101      3           3        780.129     693.335     295.679     -200.902       1      
     5      -4900101      3           3        779.295     -693.335    -295.679    -197.639       1      
------------------------------------------------------------------------------------------------------
Event 1
     1         -1         0           0        1130.064     -0.000      0.000      1130.064       -1     
     2          1         0           0        574.267      0.000       -0.000     -574.267       -1     
     3       5000001      1      

In [34]:
print('{:^12}{:^9}{:^12}{:^12}{:^12}{:^12}{:^12}{:^12}{:^12}'.format('#','id','mother1','mother2','e','px','py','pz','status'))

for n in np.where(weight_ei <= 0)[0]:
    print("Event {}".format(n))
    for i, element in enumerate(event_lhe[n].particles):
        print('{:^12}{:^9.0f}{:^12.0f}{:^12.0f}{:^12.3f}{:^12.3f}{:^12.3f}{:^12.3f}{:^12.0f}'
          .format(i+1, element.id, element.mother1, element.mother2, element.e, element.px, element.py, element.pz, element.status))
    print('-'*102)

     #         id      mother1     mother2        e           px          py          pz        status   
Event 345
     1         21         0           0        282.195      0.000       0.000      282.195        -1     
     2         -3         0           0        2964.380     -0.000      -0.000    -2964.380       -1     
     3       5000001      1           2        3086.688     -5.503      41.590    -2688.736       2      
     4       4900101      3           3        512.918     386.240     298.092     -157.939       1      
     5      -4900101      3           3        2573.770    -391.743    -256.502   -2530.798       1      
     6         21         1           2         87.496      77.746     -40.080      2.184         1      
     7         -3         1           2         72.391     -72.243      -1.510      4.368         1      
------------------------------------------------------------------------------------------------------
Event 702
     1          3         0  

In [38]:
print(len(np.where(weight_ei <= 0)))
print(len(np.where(weight_ei <= 0)[0]))

1
34


#### How to know these events are reasonable?

## 3. Load the .root Data

In [10]:
INPUT_FILE_4 = '/youwei_home/SVJ_CKKWL/s-channel_ckkwl-v2/root/svj_s_ckkwl-4.root'
INPUT_FILE_84 = '/youwei_home/SVJ_CKKWL/s-channel_ckkwl-v2/DP8/svj_ckkwl-4.root'

DATA_4 = uproot.open(INPUT_FILE_4)['Delphes;1']
DATA_84 = uproot.open(INPUT_FILE_84)['Delphes;1']

In [11]:
DATA_4.show()

Event                      TStreamerInfo              asdtype('>i4')
Event.fUniqueID            TStreamerBasicType         asjagged(asdtype('>u4'))
Event.fBits                TStreamerBasicType         asjagged(asdtype('>u4'))
Event.Number               TStreamerBasicType         asjagged(asdtype('>i8'))
Event.ReadTime             TStreamerBasicType         asjagged(asdtype('>f4'))
Event.ProcTime             TStreamerBasicType         asjagged(asdtype('>f4'))
Event.ProcessID            TStreamerBasicType         asjagged(asdtype('>i4'))
Event.MPI                  TStreamerBasicType         asjagged(asdtype('>i4'))
Event.Weight               TStreamerBasicType         asjagged(asdtype('>f4'))
Event.CrossSection         TStreamerBasicType         asjagged(asdtype('>f4'))
Event.CrossSectionError    TStreamerBasicType         asjagged(asdtype('>f4'))
Event.Scale                TStreamerBasicType         asjagged(asdtype('>f4'))
Event.AlphaQED             TStreamerBasicType         asjagged

In [12]:
DATA_84.show()

Event                      TStreamerInfo              asdtype('>i4')
Event.fUniqueID            TStreamerBasicType         asjagged(asdtype('>u4'))
Event.fBits                TStreamerBasicType         asjagged(asdtype('>u4'))
Event.Number               TStreamerBasicType         asjagged(asdtype('>i8'))
Event.ReadTime             TStreamerBasicType         asjagged(asdtype('>f4'))
Event.ProcTime             TStreamerBasicType         asjagged(asdtype('>f4'))
Event.ProcessID            TStreamerBasicType         asjagged(asdtype('>i4'))
Event.MPI                  TStreamerBasicType         asjagged(asdtype('>i4'))
Event.Weight               TStreamerBasicType         asjagged(asdtype('>f4'))
Event.CrossSection         TStreamerBasicType         asjagged(asdtype('>f4'))
Event.CrossSectionError    TStreamerBasicType         asjagged(asdtype('>f4'))
Event.Scale                TStreamerBasicType         asjagged(asdtype('>f4'))
Event.AlphaQED             TStreamerBasicType         asjagged

#### Conclusion: For the main89 .root, there are no branchs "EventLHEF.Weight" and "WeightLHEF.Weight".

### 3-1. Look over the event weight in .root file

In [13]:
# print(DATA_4['EventLHEF.Weight'].array())
print('-'*100)
# print(DATA_4['WeightLHEF.Weight'].array())
print('-'*100)
print(DATA_4['Weight.Weight'].array())
print('='*120)
print(DATA_84['EventLHEF.Weight'].array())
print('-'*100)
print(DATA_84['WeightLHEF.Weight'].array())

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
[[1.1548846e-13] [2.2193442e-13] [1.1548846e-13] ... [1.8988278e-13] [1.1548846e-13] [1.7454567e-13]]
[[1.1548845] [1.1548845] [1.1548845] ... [1.1548845] [1.1548845] [1.1548845]]
----------------------------------------------------------------------------------------------------
[[1.2337008 1.2337018 1.2337011 ... 1.2213006 1.105263 1.1409763] [1.4284981 1.4126315 1.4126256 ... 1.2456698 1.0978965 1.1334784] [1.3214043 1.3962905 1.3962675 ... 1.1211915 1.1682717 1.1740068] ... [1.3215117 1.3653513 1.365339 ... 1.1652775 1.1459279 1.1719084] [1.2299582 1.3647645 1.3646941 ... 1.1213028 1.163326 1.1698431] [1.3151894 1.3454642 1.3454514 ... 1.1731826 1.1762279 1.196033]]


In [14]:
weight_weight = DATA_4['Weight.Weight'].array()
weight_event_lhe = DATA_84['EventLHEF.Weight'].array()
weight_weight_lhe = DATA_84['WeightLHEF.Weight'].array()

In [15]:
print(len(weight_weight))
print(len(weight_event_lhe))
print(len(weight_weight_lhe))

7322
10000
10000


In [16]:
weight_weight[0]

array([1.1548846e-13], dtype=float32)

In [17]:
weight_event_lhe[0]

array([1.1548845], dtype=float32)

In [18]:
weight_weight_lhe[0]

array([1.2337008, 1.2337018, 1.2337011, 1.3213868, 1.2337008, 1.1548845,
       1.1548854, 1.1548847, 1.2337011, 1.1548845, 1.0838449, 1.0838457,
       1.0838451, 1.1548847, 1.0838449, 1.2337008, 1.2337018, 1.2337011,
       1.3213868, 1.2337008, 1.1548854, 1.1548847, 1.2337011, 1.1548845,
       1.0838449, 1.0838457, 1.0838451, 1.1548847, 1.0838449, 1.2337008,
       1.2337018, 1.2337011, 1.3213868, 1.2337008, 1.1548845, 1.1548854,
       1.1548847, 1.2337011, 1.1548845, 1.0838449, 1.0838457, 1.0838451,
       1.1548847, 1.0838449, 1.1548845, 1.1548845, 1.1548845, 1.1685663,
       1.1433241, 1.1714121, 1.1581272, 1.2325743, 1.1275935, 1.145006 ,
       1.140386 , 1.1463557, 1.2493813, 1.2331076, 1.1106575, 1.1245427,
       1.1597357, 1.1015325, 1.109006 , 1.0833071, 1.1624811, 1.1493827,
       1.1629407, 1.156851 , 1.1642998, 1.1541831, 1.1935662, 1.2384398,
       1.1096847, 1.1150798, 1.2724203, 1.072467 , 1.1747689, 1.1261953,
       1.1164421, 1.1085628, 1.1546026, 1.1747414, 

In [19]:
for i in range(len(weight_weight)):
    if weight_weight[i][0] < 0:
        print(i, weight_weight[i], weight_weight[i]*(10**9))

256 [-4.2142738e-13] [-0.00042143]
640 [-5.7245625e-13] [-0.00057246]
721 [-1.7297012e-13] [-0.00017297]
908 [-1.1548846e-13] [-0.00011549]
1541 [-1.6364887e-13] [-0.00016365]
1598 [-1.1548846e-13] [-0.00011549]
1729 [-1.7516731e-13] [-0.00017517]
1752 [-1.1548846e-13] [-0.00011549]
1932 [-1.5551548e-13] [-0.00015552]
2224 [-1.13475676e-13] [-0.00011348]
2238 [-1.1548846e-13] [-0.00011549]
2421 [-1.1548846e-13] [-0.00011549]
2442 [-1.4984495e-13] [-0.00014984]
4005 [-1.1548846e-13] [-0.00011549]
4072 [-2.1383928e-13] [-0.00021384]
4642 [-1.1548846e-13] [-0.00011549]
4943 [-1.1548846e-13] [-0.00011549]
5081 [-2.3726577e-13] [-0.00023727]
5132 [-2.4167045e-13] [-0.00024167]
5284 [-1.1548846e-13] [-0.00011549]
5366 [-1.243644e-13] [-0.00012436]
5490 [-2.3546215e-13] [-0.00023546]
6333 [-1.1548846e-13] [-0.00011549]
6484 [-1.1548846e-13] [-0.00011549]


In [20]:
for i in range(len(weight_event_lhe)):
    if weight_event_lhe[i][0] < 0:
        print(i, weight_event_lhe[i])

345 [-1.1548845]
702 [-1.1548845]
875 [-1.1548845]
985 [-1.1548845]
1245 [-1.1548845]
1606 [-1.1548845]
2095 [-1.1548845]
2173 [-1.1548845]
2352 [-1.1548845]
2379 [-1.1548845]
2625 [-1.1548845]
3014 [-1.1548845]
3031 [-1.1548845]
3278 [-1.1548845]
3305 [-1.1548845]
3796 [-1.1548845]
4390 [-1.1548845]
5452 [-1.1548845]
5538 [-1.1548845]
5695 [-1.1548845]
6303 [-1.1548845]
6355 [-1.1548845]
6720 [-1.1548845]
6752 [-1.1548845]
6915 [-1.1548845]
6980 [-1.1548845]
7129 [-1.1548845]
7190 [-1.1548845]
7298 [-1.1548845]
7467 [-1.1548845]
7891 [-1.1548845]
8295 [-1.1548845]
8641 [-1.1548845]
8846 [-1.1548845]


In [22]:
for i in range(350):
    for j in range(len(weight_weight_lhe[i])):
        if weight_weight_lhe[i][j] < 0:
            print(i, j, weight_weight_lhe[i][j])

119 57 -3.3142748
119 60 -3.590186
119 70 -3.5079489
119 73 -2.141301
119 76 -2.101908
119 81 -2.2995975
119 88 -2.461551
119 92 -4.6450577
119 98 -0.5149907
119 99 -1.1203136
119 104 -6.3466315
119 106 -0.0839467
119 107 -2.9193685
119 109 -2.6357763
119 117 -5.3490477
119 118 -3.4400294
119 119 -1.3390076
119 122 -1.2762511
119 123 -3.088752
119 125 -0.21951964
119 126 -1.3182685
119 131 -2.7741246
119 132 -0.12411015
119 134 -2.7332907
119 136 -0.06756743
119 140 -1.2933705
119 143 -1.8171582
119 146 -2.5207481
196 50 -0.14258958
196 85 -0.050837606
196 100 -0.07700706
345 0 -1.4690388
345 1 -1.6423663
345 2 -1.6423051
345 3 -2.1378603
345 4 -1.3747436
345 5 -1.3286824
345 6 -1.4823146
345 7 -1.4822603
345 8 -1.9203705
345 9 -1.2449311
345 10 -1.2069967
345 11 -1.3440896
345 12 -1.3440413
345 13 -1.7332278
345 14 -1.1321533
345 15 -1.2768817
345 16 -1.4209714
345 17 -1.4209206
345 18 -1.8283029
345 19 -1.1981082
345 20 -1.282495
345 21 -1.28245
345 22 -1.6423051
345 23 -1.0849748
34